apiVersion: v1
kind: Pod
metadata:
  name: wav2vec2-asr-pod
  namespace: default
  labels:
    app: wav2vec2-asr
    version: v1
spec:
  containers:
  - name: asr-container
    image: wav2vec2-asr:latest
    imagePullPolicy: IfNotPresent
    
    # Resource requests and limits
    resources:
      requests:
        memory: "2Gi"
        cpu: "1"
      limits:
        memory: "4Gi"
        cpu: "2"
    
    # Environment variables
    env:
    - name: DEFAULT_SAMPLING_RATE
      value: "16000"
    - name: PYTHONUNBUFFERED
      value: "1"
    
    # Volume mounts
    volumeMounts:
    - name: audio-input
      mountPath: /app/input
    - name: transcription-output
      mountPath: /app/output
    
    # Health checks (optional)
    livenessProbe:
      exec:
        command:
        - sh
        - -c
        - "test -f /app/hindi.pt && echo 'healthy'"
      initialDelaySeconds: 30
      periodSeconds: 60
    
    # Standard input/output
    stdin: false
    tty: false
  
  # Volumes for input/output
  volumes:
  - name: audio-input
    emptyDir: {}
  - name: transcription-output
    emptyDir: {}
  
  # Pod restart policy
  restartPolicy: OnFailure
  
  # Node selector (optional - specify CPU node)
  nodeSelector:
    kubernetes.io/hostname: master1
